# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/sf_csc4140/119010009_HW_6/hw6_pathtracer/hw6_pathtracer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/sf_csc4140/119010009_HW_6/hw6_pathtracer/hw6_pathtracer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_csc4140/119010009_HW_6/hw6_pathtracer/hw6_pathtracer/CMakeFiles /media/sf_csc4140/119010009_HW_6/hw6_pathtracer/hw6_pathtracer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/sf_csc4140/119010009_HW_6/hw6_pathtracer/hw6_pathtracer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pathtracer

# Build rule for target.
pathtracer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pathtracer
.PHONY : pathtracer

# fast build rule for target.
pathtracer/fast:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/build
.PHONY : pathtracer/fast

#=============================================================================
# Target rules for targets named CGL

# Build rule for target.
CGL: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGL
.PHONY : CGL

# fast build rule for target.
CGL/fast:
	$(MAKE) -f CGL/CMakeFiles/CGL.dir/build.make CGL/CMakeFiles/CGL.dir/build
.PHONY : CGL/fast

#=============================================================================
# Target rules for targets named glew

# Build rule for target.
glew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glew
.PHONY : glew

# fast build rule for target.
glew/fast:
	$(MAKE) -f CGL/deps/glew/CMakeFiles/glew.dir/build.make CGL/deps/glew/CMakeFiles/glew.dir/build
.PHONY : glew/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CGL/deps/glfw/CMakeFiles/uninstall.dir/build.make CGL/deps/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f CGL/deps/glfw/src/CMakeFiles/glfw.dir/build.make CGL/deps/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/application/application.o: src/application/application.cpp.o

.PHONY : src/application/application.o

# target to build an object file
src/application/application.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/application.cpp.o
.PHONY : src/application/application.cpp.o

src/application/application.i: src/application/application.cpp.i

.PHONY : src/application/application.i

# target to preprocess a source file
src/application/application.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/application.cpp.i
.PHONY : src/application/application.cpp.i

src/application/application.s: src/application/application.cpp.s

.PHONY : src/application/application.s

# target to generate assembly for a file
src/application/application.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/application.cpp.s
.PHONY : src/application/application.cpp.s

src/application/main.o: src/application/main.cpp.o

.PHONY : src/application/main.o

# target to build an object file
src/application/main.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/main.cpp.o
.PHONY : src/application/main.cpp.o

src/application/main.i: src/application/main.cpp.i

.PHONY : src/application/main.i

# target to preprocess a source file
src/application/main.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/main.cpp.i
.PHONY : src/application/main.cpp.i

src/application/main.s: src/application/main.cpp.s

.PHONY : src/application/main.s

# target to generate assembly for a file
src/application/main.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/main.cpp.s
.PHONY : src/application/main.cpp.s

src/application/meshEdit.o: src/application/meshEdit.cpp.o

.PHONY : src/application/meshEdit.o

# target to build an object file
src/application/meshEdit.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/meshEdit.cpp.o
.PHONY : src/application/meshEdit.cpp.o

src/application/meshEdit.i: src/application/meshEdit.cpp.i

.PHONY : src/application/meshEdit.i

# target to preprocess a source file
src/application/meshEdit.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/meshEdit.cpp.i
.PHONY : src/application/meshEdit.cpp.i

src/application/meshEdit.s: src/application/meshEdit.cpp.s

.PHONY : src/application/meshEdit.s

# target to generate assembly for a file
src/application/meshEdit.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/meshEdit.cpp.s
.PHONY : src/application/meshEdit.cpp.s

src/application/visual_debugger.o: src/application/visual_debugger.cpp.o

.PHONY : src/application/visual_debugger.o

# target to build an object file
src/application/visual_debugger.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/visual_debugger.cpp.o
.PHONY : src/application/visual_debugger.cpp.o

src/application/visual_debugger.i: src/application/visual_debugger.cpp.i

.PHONY : src/application/visual_debugger.i

# target to preprocess a source file
src/application/visual_debugger.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/visual_debugger.cpp.i
.PHONY : src/application/visual_debugger.cpp.i

src/application/visual_debugger.s: src/application/visual_debugger.cpp.s

.PHONY : src/application/visual_debugger.s

# target to generate assembly for a file
src/application/visual_debugger.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/application/visual_debugger.cpp.s
.PHONY : src/application/visual_debugger.cpp.s

src/imgui/backends/imgui_impl_glfw.o: src/imgui/backends/imgui_impl_glfw.cpp.o

.PHONY : src/imgui/backends/imgui_impl_glfw.o

# target to build an object file
src/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : src/imgui/backends/imgui_impl_glfw.cpp.o

src/imgui/backends/imgui_impl_glfw.i: src/imgui/backends/imgui_impl_glfw.cpp.i

.PHONY : src/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
src/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : src/imgui/backends/imgui_impl_glfw.cpp.i

src/imgui/backends/imgui_impl_glfw.s: src/imgui/backends/imgui_impl_glfw.cpp.s

.PHONY : src/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
src/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : src/imgui/backends/imgui_impl_glfw.cpp.s

src/imgui/backends/imgui_impl_opengl2.o: src/imgui/backends/imgui_impl_opengl2.cpp.o

.PHONY : src/imgui/backends/imgui_impl_opengl2.o

# target to build an object file
src/imgui/backends/imgui_impl_opengl2.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_opengl2.cpp.o
.PHONY : src/imgui/backends/imgui_impl_opengl2.cpp.o

src/imgui/backends/imgui_impl_opengl2.i: src/imgui/backends/imgui_impl_opengl2.cpp.i

.PHONY : src/imgui/backends/imgui_impl_opengl2.i

# target to preprocess a source file
src/imgui/backends/imgui_impl_opengl2.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_opengl2.cpp.i
.PHONY : src/imgui/backends/imgui_impl_opengl2.cpp.i

src/imgui/backends/imgui_impl_opengl2.s: src/imgui/backends/imgui_impl_opengl2.cpp.s

.PHONY : src/imgui/backends/imgui_impl_opengl2.s

# target to generate assembly for a file
src/imgui/backends/imgui_impl_opengl2.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/backends/imgui_impl_opengl2.cpp.s
.PHONY : src/imgui/backends/imgui_impl_opengl2.cpp.s

src/imgui/imgui.o: src/imgui/imgui.cpp.o

.PHONY : src/imgui/imgui.o

# target to build an object file
src/imgui/imgui.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui.cpp.o
.PHONY : src/imgui/imgui.cpp.o

src/imgui/imgui.i: src/imgui/imgui.cpp.i

.PHONY : src/imgui/imgui.i

# target to preprocess a source file
src/imgui/imgui.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui.cpp.i
.PHONY : src/imgui/imgui.cpp.i

src/imgui/imgui.s: src/imgui/imgui.cpp.s

.PHONY : src/imgui/imgui.s

# target to generate assembly for a file
src/imgui/imgui.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui.cpp.s
.PHONY : src/imgui/imgui.cpp.s

src/imgui/imgui_draw.o: src/imgui/imgui_draw.cpp.o

.PHONY : src/imgui/imgui_draw.o

# target to build an object file
src/imgui/imgui_draw.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_draw.cpp.o
.PHONY : src/imgui/imgui_draw.cpp.o

src/imgui/imgui_draw.i: src/imgui/imgui_draw.cpp.i

.PHONY : src/imgui/imgui_draw.i

# target to preprocess a source file
src/imgui/imgui_draw.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_draw.cpp.i
.PHONY : src/imgui/imgui_draw.cpp.i

src/imgui/imgui_draw.s: src/imgui/imgui_draw.cpp.s

.PHONY : src/imgui/imgui_draw.s

# target to generate assembly for a file
src/imgui/imgui_draw.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_draw.cpp.s
.PHONY : src/imgui/imgui_draw.cpp.s

src/imgui/imgui_tables.o: src/imgui/imgui_tables.cpp.o

.PHONY : src/imgui/imgui_tables.o

# target to build an object file
src/imgui/imgui_tables.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_tables.cpp.o
.PHONY : src/imgui/imgui_tables.cpp.o

src/imgui/imgui_tables.i: src/imgui/imgui_tables.cpp.i

.PHONY : src/imgui/imgui_tables.i

# target to preprocess a source file
src/imgui/imgui_tables.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_tables.cpp.i
.PHONY : src/imgui/imgui_tables.cpp.i

src/imgui/imgui_tables.s: src/imgui/imgui_tables.cpp.s

.PHONY : src/imgui/imgui_tables.s

# target to generate assembly for a file
src/imgui/imgui_tables.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_tables.cpp.s
.PHONY : src/imgui/imgui_tables.cpp.s

src/imgui/imgui_widgets.o: src/imgui/imgui_widgets.cpp.o

.PHONY : src/imgui/imgui_widgets.o

# target to build an object file
src/imgui/imgui_widgets.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_widgets.cpp.o
.PHONY : src/imgui/imgui_widgets.cpp.o

src/imgui/imgui_widgets.i: src/imgui/imgui_widgets.cpp.i

.PHONY : src/imgui/imgui_widgets.i

# target to preprocess a source file
src/imgui/imgui_widgets.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_widgets.cpp.i
.PHONY : src/imgui/imgui_widgets.cpp.i

src/imgui/imgui_widgets.s: src/imgui/imgui_widgets.cpp.s

.PHONY : src/imgui/imgui_widgets.s

# target to generate assembly for a file
src/imgui/imgui_widgets.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/imgui/imgui_widgets.cpp.s
.PHONY : src/imgui/imgui_widgets.cpp.s

src/pathtracer/advanced_bsdf.o: src/pathtracer/advanced_bsdf.cpp.o

.PHONY : src/pathtracer/advanced_bsdf.o

# target to build an object file
src/pathtracer/advanced_bsdf.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/advanced_bsdf.cpp.o
.PHONY : src/pathtracer/advanced_bsdf.cpp.o

src/pathtracer/advanced_bsdf.i: src/pathtracer/advanced_bsdf.cpp.i

.PHONY : src/pathtracer/advanced_bsdf.i

# target to preprocess a source file
src/pathtracer/advanced_bsdf.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/advanced_bsdf.cpp.i
.PHONY : src/pathtracer/advanced_bsdf.cpp.i

src/pathtracer/advanced_bsdf.s: src/pathtracer/advanced_bsdf.cpp.s

.PHONY : src/pathtracer/advanced_bsdf.s

# target to generate assembly for a file
src/pathtracer/advanced_bsdf.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/advanced_bsdf.cpp.s
.PHONY : src/pathtracer/advanced_bsdf.cpp.s

src/pathtracer/camera_lens.o: src/pathtracer/camera_lens.cpp.o

.PHONY : src/pathtracer/camera_lens.o

# target to build an object file
src/pathtracer/camera_lens.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/camera_lens.cpp.o
.PHONY : src/pathtracer/camera_lens.cpp.o

src/pathtracer/camera_lens.i: src/pathtracer/camera_lens.cpp.i

.PHONY : src/pathtracer/camera_lens.i

# target to preprocess a source file
src/pathtracer/camera_lens.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/camera_lens.cpp.i
.PHONY : src/pathtracer/camera_lens.cpp.i

src/pathtracer/camera_lens.s: src/pathtracer/camera_lens.cpp.s

.PHONY : src/pathtracer/camera_lens.s

# target to generate assembly for a file
src/pathtracer/camera_lens.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/camera_lens.cpp.s
.PHONY : src/pathtracer/camera_lens.cpp.s

src/pathtracer/raytraced_renderer.o: src/pathtracer/raytraced_renderer.cpp.o

.PHONY : src/pathtracer/raytraced_renderer.o

# target to build an object file
src/pathtracer/raytraced_renderer.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/raytraced_renderer.cpp.o
.PHONY : src/pathtracer/raytraced_renderer.cpp.o

src/pathtracer/raytraced_renderer.i: src/pathtracer/raytraced_renderer.cpp.i

.PHONY : src/pathtracer/raytraced_renderer.i

# target to preprocess a source file
src/pathtracer/raytraced_renderer.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/raytraced_renderer.cpp.i
.PHONY : src/pathtracer/raytraced_renderer.cpp.i

src/pathtracer/raytraced_renderer.s: src/pathtracer/raytraced_renderer.cpp.s

.PHONY : src/pathtracer/raytraced_renderer.s

# target to generate assembly for a file
src/pathtracer/raytraced_renderer.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/raytraced_renderer.cpp.s
.PHONY : src/pathtracer/raytraced_renderer.cpp.s

src/pathtracer/sampler.o: src/pathtracer/sampler.cpp.o

.PHONY : src/pathtracer/sampler.o

# target to build an object file
src/pathtracer/sampler.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/sampler.cpp.o
.PHONY : src/pathtracer/sampler.cpp.o

src/pathtracer/sampler.i: src/pathtracer/sampler.cpp.i

.PHONY : src/pathtracer/sampler.i

# target to preprocess a source file
src/pathtracer/sampler.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/sampler.cpp.i
.PHONY : src/pathtracer/sampler.cpp.i

src/pathtracer/sampler.s: src/pathtracer/sampler.cpp.s

.PHONY : src/pathtracer/sampler.s

# target to generate assembly for a file
src/pathtracer/sampler.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/pathtracer/sampler.cpp.s
.PHONY : src/pathtracer/sampler.cpp.s

src/scene/collada/camera_info.o: src/scene/collada/camera_info.cpp.o

.PHONY : src/scene/collada/camera_info.o

# target to build an object file
src/scene/collada/camera_info.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/camera_info.cpp.o
.PHONY : src/scene/collada/camera_info.cpp.o

src/scene/collada/camera_info.i: src/scene/collada/camera_info.cpp.i

.PHONY : src/scene/collada/camera_info.i

# target to preprocess a source file
src/scene/collada/camera_info.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/camera_info.cpp.i
.PHONY : src/scene/collada/camera_info.cpp.i

src/scene/collada/camera_info.s: src/scene/collada/camera_info.cpp.s

.PHONY : src/scene/collada/camera_info.s

# target to generate assembly for a file
src/scene/collada/camera_info.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/camera_info.cpp.s
.PHONY : src/scene/collada/camera_info.cpp.s

src/scene/collada/collada.o: src/scene/collada/collada.cpp.o

.PHONY : src/scene/collada/collada.o

# target to build an object file
src/scene/collada/collada.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/collada.cpp.o
.PHONY : src/scene/collada/collada.cpp.o

src/scene/collada/collada.i: src/scene/collada/collada.cpp.i

.PHONY : src/scene/collada/collada.i

# target to preprocess a source file
src/scene/collada/collada.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/collada.cpp.i
.PHONY : src/scene/collada/collada.cpp.i

src/scene/collada/collada.s: src/scene/collada/collada.cpp.s

.PHONY : src/scene/collada/collada.s

# target to generate assembly for a file
src/scene/collada/collada.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/collada.cpp.s
.PHONY : src/scene/collada/collada.cpp.s

src/scene/collada/light_info.o: src/scene/collada/light_info.cpp.o

.PHONY : src/scene/collada/light_info.o

# target to build an object file
src/scene/collada/light_info.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/light_info.cpp.o
.PHONY : src/scene/collada/light_info.cpp.o

src/scene/collada/light_info.i: src/scene/collada/light_info.cpp.i

.PHONY : src/scene/collada/light_info.i

# target to preprocess a source file
src/scene/collada/light_info.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/light_info.cpp.i
.PHONY : src/scene/collada/light_info.cpp.i

src/scene/collada/light_info.s: src/scene/collada/light_info.cpp.s

.PHONY : src/scene/collada/light_info.s

# target to generate assembly for a file
src/scene/collada/light_info.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/light_info.cpp.s
.PHONY : src/scene/collada/light_info.cpp.s

src/scene/collada/material_info.o: src/scene/collada/material_info.cpp.o

.PHONY : src/scene/collada/material_info.o

# target to build an object file
src/scene/collada/material_info.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/material_info.cpp.o
.PHONY : src/scene/collada/material_info.cpp.o

src/scene/collada/material_info.i: src/scene/collada/material_info.cpp.i

.PHONY : src/scene/collada/material_info.i

# target to preprocess a source file
src/scene/collada/material_info.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/material_info.cpp.i
.PHONY : src/scene/collada/material_info.cpp.i

src/scene/collada/material_info.s: src/scene/collada/material_info.cpp.s

.PHONY : src/scene/collada/material_info.s

# target to generate assembly for a file
src/scene/collada/material_info.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/material_info.cpp.s
.PHONY : src/scene/collada/material_info.cpp.s

src/scene/collada/polymesh_info.o: src/scene/collada/polymesh_info.cpp.o

.PHONY : src/scene/collada/polymesh_info.o

# target to build an object file
src/scene/collada/polymesh_info.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/polymesh_info.cpp.o
.PHONY : src/scene/collada/polymesh_info.cpp.o

src/scene/collada/polymesh_info.i: src/scene/collada/polymesh_info.cpp.i

.PHONY : src/scene/collada/polymesh_info.i

# target to preprocess a source file
src/scene/collada/polymesh_info.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/polymesh_info.cpp.i
.PHONY : src/scene/collada/polymesh_info.cpp.i

src/scene/collada/polymesh_info.s: src/scene/collada/polymesh_info.cpp.s

.PHONY : src/scene/collada/polymesh_info.s

# target to generate assembly for a file
src/scene/collada/polymesh_info.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/polymesh_info.cpp.s
.PHONY : src/scene/collada/polymesh_info.cpp.s

src/scene/collada/sphere_info.o: src/scene/collada/sphere_info.cpp.o

.PHONY : src/scene/collada/sphere_info.o

# target to build an object file
src/scene/collada/sphere_info.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/sphere_info.cpp.o
.PHONY : src/scene/collada/sphere_info.cpp.o

src/scene/collada/sphere_info.i: src/scene/collada/sphere_info.cpp.i

.PHONY : src/scene/collada/sphere_info.i

# target to preprocess a source file
src/scene/collada/sphere_info.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/sphere_info.cpp.i
.PHONY : src/scene/collada/sphere_info.cpp.i

src/scene/collada/sphere_info.s: src/scene/collada/sphere_info.cpp.s

.PHONY : src/scene/collada/sphere_info.s

# target to generate assembly for a file
src/scene/collada/sphere_info.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/collada/sphere_info.cpp.s
.PHONY : src/scene/collada/sphere_info.cpp.s

src/scene/environment_light.o: src/scene/environment_light.cpp.o

.PHONY : src/scene/environment_light.o

# target to build an object file
src/scene/environment_light.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/environment_light.cpp.o
.PHONY : src/scene/environment_light.cpp.o

src/scene/environment_light.i: src/scene/environment_light.cpp.i

.PHONY : src/scene/environment_light.i

# target to preprocess a source file
src/scene/environment_light.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/environment_light.cpp.i
.PHONY : src/scene/environment_light.cpp.i

src/scene/environment_light.s: src/scene/environment_light.cpp.s

.PHONY : src/scene/environment_light.s

# target to generate assembly for a file
src/scene/environment_light.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/environment_light.cpp.s
.PHONY : src/scene/environment_light.cpp.s

src/scene/gl_scene/mesh.o: src/scene/gl_scene/mesh.cpp.o

.PHONY : src/scene/gl_scene/mesh.o

# target to build an object file
src/scene/gl_scene/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/mesh.cpp.o
.PHONY : src/scene/gl_scene/mesh.cpp.o

src/scene/gl_scene/mesh.i: src/scene/gl_scene/mesh.cpp.i

.PHONY : src/scene/gl_scene/mesh.i

# target to preprocess a source file
src/scene/gl_scene/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/mesh.cpp.i
.PHONY : src/scene/gl_scene/mesh.cpp.i

src/scene/gl_scene/mesh.s: src/scene/gl_scene/mesh.cpp.s

.PHONY : src/scene/gl_scene/mesh.s

# target to generate assembly for a file
src/scene/gl_scene/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/mesh.cpp.s
.PHONY : src/scene/gl_scene/mesh.cpp.s

src/scene/gl_scene/scene.o: src/scene/gl_scene/scene.cpp.o

.PHONY : src/scene/gl_scene/scene.o

# target to build an object file
src/scene/gl_scene/scene.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/scene.cpp.o
.PHONY : src/scene/gl_scene/scene.cpp.o

src/scene/gl_scene/scene.i: src/scene/gl_scene/scene.cpp.i

.PHONY : src/scene/gl_scene/scene.i

# target to preprocess a source file
src/scene/gl_scene/scene.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/scene.cpp.i
.PHONY : src/scene/gl_scene/scene.cpp.i

src/scene/gl_scene/scene.s: src/scene/gl_scene/scene.cpp.s

.PHONY : src/scene/gl_scene/scene.s

# target to generate assembly for a file
src/scene/gl_scene/scene.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/scene.cpp.s
.PHONY : src/scene/gl_scene/scene.cpp.s

src/scene/gl_scene/sphere.o: src/scene/gl_scene/sphere.cpp.o

.PHONY : src/scene/gl_scene/sphere.o

# target to build an object file
src/scene/gl_scene/sphere.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/sphere.cpp.o
.PHONY : src/scene/gl_scene/sphere.cpp.o

src/scene/gl_scene/sphere.i: src/scene/gl_scene/sphere.cpp.i

.PHONY : src/scene/gl_scene/sphere.i

# target to preprocess a source file
src/scene/gl_scene/sphere.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/sphere.cpp.i
.PHONY : src/scene/gl_scene/sphere.cpp.i

src/scene/gl_scene/sphere.s: src/scene/gl_scene/sphere.cpp.s

.PHONY : src/scene/gl_scene/sphere.s

# target to generate assembly for a file
src/scene/gl_scene/sphere.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/gl_scene/sphere.cpp.s
.PHONY : src/scene/gl_scene/sphere.cpp.s

src/scene/object.o: src/scene/object.cpp.o

.PHONY : src/scene/object.o

# target to build an object file
src/scene/object.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/object.cpp.o
.PHONY : src/scene/object.cpp.o

src/scene/object.i: src/scene/object.cpp.i

.PHONY : src/scene/object.i

# target to preprocess a source file
src/scene/object.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/object.cpp.i
.PHONY : src/scene/object.cpp.i

src/scene/object.s: src/scene/object.cpp.s

.PHONY : src/scene/object.s

# target to generate assembly for a file
src/scene/object.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/scene/object.cpp.s
.PHONY : src/scene/object.cpp.s

src/util/halfEdgeMesh.o: src/util/halfEdgeMesh.cpp.o

.PHONY : src/util/halfEdgeMesh.o

# target to build an object file
src/util/halfEdgeMesh.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/halfEdgeMesh.cpp.o
.PHONY : src/util/halfEdgeMesh.cpp.o

src/util/halfEdgeMesh.i: src/util/halfEdgeMesh.cpp.i

.PHONY : src/util/halfEdgeMesh.i

# target to preprocess a source file
src/util/halfEdgeMesh.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/halfEdgeMesh.cpp.i
.PHONY : src/util/halfEdgeMesh.cpp.i

src/util/halfEdgeMesh.s: src/util/halfEdgeMesh.cpp.s

.PHONY : src/util/halfEdgeMesh.s

# target to generate assembly for a file
src/util/halfEdgeMesh.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/halfEdgeMesh.cpp.s
.PHONY : src/util/halfEdgeMesh.cpp.s

src/util/lodepng.o: src/util/lodepng.cpp.o

.PHONY : src/util/lodepng.o

# target to build an object file
src/util/lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/lodepng.cpp.o
.PHONY : src/util/lodepng.cpp.o

src/util/lodepng.i: src/util/lodepng.cpp.i

.PHONY : src/util/lodepng.i

# target to preprocess a source file
src/util/lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/lodepng.cpp.i
.PHONY : src/util/lodepng.cpp.i

src/util/lodepng.s: src/util/lodepng.cpp.s

.PHONY : src/util/lodepng.s

# target to generate assembly for a file
src/util/lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/lodepng.cpp.s
.PHONY : src/util/lodepng.cpp.s

src/util/sphere_drawing.o: src/util/sphere_drawing.cpp.o

.PHONY : src/util/sphere_drawing.o

# target to build an object file
src/util/sphere_drawing.cpp.o:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/sphere_drawing.cpp.o
.PHONY : src/util/sphere_drawing.cpp.o

src/util/sphere_drawing.i: src/util/sphere_drawing.cpp.i

.PHONY : src/util/sphere_drawing.i

# target to preprocess a source file
src/util/sphere_drawing.cpp.i:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/sphere_drawing.cpp.i
.PHONY : src/util/sphere_drawing.cpp.i

src/util/sphere_drawing.s: src/util/sphere_drawing.cpp.s

.PHONY : src/util/sphere_drawing.s

# target to generate assembly for a file
src/util/sphere_drawing.cpp.s:
	$(MAKE) -f CMakeFiles/pathtracer.dir/build.make CMakeFiles/pathtracer.dir/src/util/sphere_drawing.cpp.s
.PHONY : src/util/sphere_drawing.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... pathtracer"
	@echo "... CGL"
	@echo "... glew"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... src/application/application.o"
	@echo "... src/application/application.i"
	@echo "... src/application/application.s"
	@echo "... src/application/main.o"
	@echo "... src/application/main.i"
	@echo "... src/application/main.s"
	@echo "... src/application/meshEdit.o"
	@echo "... src/application/meshEdit.i"
	@echo "... src/application/meshEdit.s"
	@echo "... src/application/visual_debugger.o"
	@echo "... src/application/visual_debugger.i"
	@echo "... src/application/visual_debugger.s"
	@echo "... src/imgui/backends/imgui_impl_glfw.o"
	@echo "... src/imgui/backends/imgui_impl_glfw.i"
	@echo "... src/imgui/backends/imgui_impl_glfw.s"
	@echo "... src/imgui/backends/imgui_impl_opengl2.o"
	@echo "... src/imgui/backends/imgui_impl_opengl2.i"
	@echo "... src/imgui/backends/imgui_impl_opengl2.s"
	@echo "... src/imgui/imgui.o"
	@echo "... src/imgui/imgui.i"
	@echo "... src/imgui/imgui.s"
	@echo "... src/imgui/imgui_draw.o"
	@echo "... src/imgui/imgui_draw.i"
	@echo "... src/imgui/imgui_draw.s"
	@echo "... src/imgui/imgui_tables.o"
	@echo "... src/imgui/imgui_tables.i"
	@echo "... src/imgui/imgui_tables.s"
	@echo "... src/imgui/imgui_widgets.o"
	@echo "... src/imgui/imgui_widgets.i"
	@echo "... src/imgui/imgui_widgets.s"
	@echo "... src/pathtracer/advanced_bsdf.o"
	@echo "... src/pathtracer/advanced_bsdf.i"
	@echo "... src/pathtracer/advanced_bsdf.s"
	@echo "... src/pathtracer/camera_lens.o"
	@echo "... src/pathtracer/camera_lens.i"
	@echo "... src/pathtracer/camera_lens.s"
	@echo "... src/pathtracer/raytraced_renderer.o"
	@echo "... src/pathtracer/raytraced_renderer.i"
	@echo "... src/pathtracer/raytraced_renderer.s"
	@echo "... src/pathtracer/sampler.o"
	@echo "... src/pathtracer/sampler.i"
	@echo "... src/pathtracer/sampler.s"
	@echo "... src/scene/collada/camera_info.o"
	@echo "... src/scene/collada/camera_info.i"
	@echo "... src/scene/collada/camera_info.s"
	@echo "... src/scene/collada/collada.o"
	@echo "... src/scene/collada/collada.i"
	@echo "... src/scene/collada/collada.s"
	@echo "... src/scene/collada/light_info.o"
	@echo "... src/scene/collada/light_info.i"
	@echo "... src/scene/collada/light_info.s"
	@echo "... src/scene/collada/material_info.o"
	@echo "... src/scene/collada/material_info.i"
	@echo "... src/scene/collada/material_info.s"
	@echo "... src/scene/collada/polymesh_info.o"
	@echo "... src/scene/collada/polymesh_info.i"
	@echo "... src/scene/collada/polymesh_info.s"
	@echo "... src/scene/collada/sphere_info.o"
	@echo "... src/scene/collada/sphere_info.i"
	@echo "... src/scene/collada/sphere_info.s"
	@echo "... src/scene/environment_light.o"
	@echo "... src/scene/environment_light.i"
	@echo "... src/scene/environment_light.s"
	@echo "... src/scene/gl_scene/mesh.o"
	@echo "... src/scene/gl_scene/mesh.i"
	@echo "... src/scene/gl_scene/mesh.s"
	@echo "... src/scene/gl_scene/scene.o"
	@echo "... src/scene/gl_scene/scene.i"
	@echo "... src/scene/gl_scene/scene.s"
	@echo "... src/scene/gl_scene/sphere.o"
	@echo "... src/scene/gl_scene/sphere.i"
	@echo "... src/scene/gl_scene/sphere.s"
	@echo "... src/scene/object.o"
	@echo "... src/scene/object.i"
	@echo "... src/scene/object.s"
	@echo "... src/util/halfEdgeMesh.o"
	@echo "... src/util/halfEdgeMesh.i"
	@echo "... src/util/halfEdgeMesh.s"
	@echo "... src/util/lodepng.o"
	@echo "... src/util/lodepng.i"
	@echo "... src/util/lodepng.s"
	@echo "... src/util/sphere_drawing.o"
	@echo "... src/util/sphere_drawing.i"
	@echo "... src/util/sphere_drawing.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

